include: analysis_options.yaml

analyzer:
  exclude:
    - lib/**/**.freezed.dart
    - lib/**/**.g.dart
  errors:
    invalid_annotation_target: ignore
linter:
  rules:
    prefer_single_quotes: true
    require_trailing_commas: true