name: if_then_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  firebase_core: ^1.24.0
  cloud_firestore: ^3.5.1
  firebase_auth: ^3.11.2
  font_awesome_flutter: ^10.2.1
  google_fonts: ^3.0.1
  firebase_messaging: ^13.1.0
  flutter_local_notifications: ^12.0.0
  google_sign_in: ^5.4.2
  cloud_functions: ^3.3.9
  sign_in_with_apple: ^4.1.0
  crypto: ^3.0.2
  sign_button: ^2.0.2
  flutter_easyloading: ^3.0.5
  hooks_riverpod: ^2.0.2

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  pedantic_mono: ^1.20.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  image_path: "images/web_hi_res_512.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "images/IfThen_Icon_foreground.png"
  ios: true
  image_path_ios: "images/web_hi_res_512.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - images/gachagacha.png
